[profile.default]
src = "src"
out = "out"
libs = ["lib"]
verbosity = 3
# Mumabi Testnet
chain_id = 80001

[rpc_endpoints]
localhost = "http://localhost:8545"
# Ethereum
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
# Polygon
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
# Filecoin
calibration = "${CALIBRATION_RPC_URL}"
filecoin = "${FILECOIN_RPC_URL}"

[etherscan]
# Ethereum
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://sepolia.etherscan.io/" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
# Polygon: $POLYGONSCAN_API_KEY not working, see: https://github.com/foundry-rs/foundry/issues/4484
mumbai = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api"}
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api"}

[fmt]
line_length = 80
wrap_comments = true
tab_width = 2
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config